// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: devices.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (id, created_at, updated_at, codetag)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at, updated_at, codetag
`

type CreateDeviceParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Codetag   string
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, createDevice,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Codetag,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Codetag,
	)
	return i, err
}
